set(COMMON_BUILD_CPP_SOURCES
    ../common/src/controller/logcontroller.cpp
    ../common/src/controller/logcontroller.h
    ../common/src/controller/resourcecontroller.cpp
    ../common/src/controller/resourcecontroller.h
    ../common/src/controller/mqttcontroller.cpp
    ../common/src/controller/mqttcontroller.h
    ../common/src/controller/sharedcontroller.cpp
    ../common/src/controller/sharedcontroller.h
    ../common/src/utils/logger.cpp
    ../common/src/utils/logger.h
)
