set(COMMON_BUILD_CPP_SOURCES
    ../common/src/controller/logcontroller.cpp
    ../common/src/controller/logcontroller.h
    ../common/src/controller/resourcecontroller.cpp
    ../common/src/controller/resourcecontroller.h
    ../common/src/controller/mqttcontroller.cpp
    ../common/src/controller/mqttcontroller.h
    ../common/src/controller/sharedcontroller.cpp
    ../common/src/controller/sharedcontroller.h
    ../common/src/controller/uisettingcontroller.cpp
    ../common/src/controller/uisettingcontroller.h
    ../common/src/controller/screentransitioncontroller.h
    ../common/src/controller/screentransitioncontroller.cpp
    ../common/src/topics/topics.cpp
    ../common/src/topics/topics.h
    ../common/src/topics/testtopic.cpp
    ../common/src/topics/testtopic.h
    ../common/src/utils/logger.cpp
    ../common/src/utils/logger.h
    ../common/src/utils/screenid.h
    ../common/src/utils/dummyresponse.cpp
    ../common/src/utils/dummyresponse.h
)
